os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

install:
  - set CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  - scripts\speck\build_win.bat

artifacts:
  - path: build_win32.zip
    name: build_win32

  - path: build_win64.zip
    name: build_win64

